# Generated by Django 5.2.5 on 2026-02-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailCode',
            new_name='VerificationCode',
        ),
    ]
