# Generated by Django 5.2.6 on 2025-09-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_knowyoucustomer_knowyourcustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowyourcustomer',
            old_name='document_pic',
            new_name='document_file',
        ),
        migrations.AlterField(
            model_name='knowyourcustomer',
            name='status_tracking',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
