# Generated by Django 5.2.6 on 2025-11-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_rename_building_nubmer_address_building_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='appartment_number',
            new_name='apartment_number',
        ),
    ]
