# Generated by Django 5.2.6 on 2025-12-27 12:18

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_status_transaction_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paymob_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='paymob_payment_token',
            new_name='payment_token',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_provider',
            field=models.CharField(choices=[('PayMob', 'PayMob')], default='PayMob', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_order_id',
            field=models.CharField(default=transactions.models.dufault_merchant_order_id, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', editable=False, max_length=20),
        ),
    ]
