# Generated by Django 5.2.5 on 2026-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencymail',
            name='purpose',
            field=models.CharField(max_length=100),
        ),
    ]
