# Generated by Django 5.2.5 on 2026-01-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_idempotencymail_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('provider_response_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('to_email', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IdempotencyMail',
        ),
    ]
