# Generated by Django 5.2.5 on 2026-01-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailevent_delete_idempotencymail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
