# Generated by Django 5.2.5 on 2026-01-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_emailevent_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailevent',
            old_name='key',
            new_name='idempotent_key',
        ),
    ]
