# Generated by Django 5.2.6 on 2025-10-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paymob_order_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
