# Generated by Django 5.2.6 on 2025-09-27 04:52

import customers.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_document_pic_knowyourcustomer_document_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='EG', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='main_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[customers.validators.valid_age]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, help_text='Name must match the name in the document to succeed validation', max_length=50, null=True, validators=[customers.validators.validate_customer_name]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[customers.validators.validate_phone]),
        ),
    ]
