# Generated by Django 5.2.6 on 2025-11-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_full_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='building_nubmer',
            new_name='building_number',
        ),
    ]
